from time import sleep
print("welcome to doge town")
sleep(1)
print("printing doge in...")
sleep(1)
print("3")
sleep(1)
print("2")
sleep(1)
print("1")
sleep(1)
print("─ ─ ─ ─ ─ ─ ─ ─ ─ ▄ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ▄ ─ ─ ─ ─")
print(" ")
sleep(0.1)
print("─ ─ ─ ─ ─ ─ ─ ─ ▌ ▒ █ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ▄ ▀ ▒ ▌ ─ ─ ─")
print(" ")
sleep(0.1)
print("─ ─ ─ ─ ─ ─ ─ ─ ▌ ▒ ▒ ▀ ▄ ─ ─ ─ ─ ─ ─ ─ ▄ ▀ ▒ ▒ ▒ ▐ ─ ─ ─")
print(" ")
sleep(0.1)
print("─ ─ ─ ─ ─ ─ ─ ▐ ▄ ▀ ▒ ▒ ▀ ▀ ▀ ▀ ▄ ▄ ▄ ▀ ▒ ▒ ▒ ▒ ▒ ▐ ─ ─ ─")
print(" ")
sleep(0.1)
print("─ ─ ─ ─ ─ ▄ ▄ ▀ ▒ ▒ ▒ ▒ ▒ ▒ ▒ ▒ ▒ ▒ ▒ █ ▒ ▒ ▄ █ ▒ ▐ ─ ─ ─")
print(" ")
sleep(0.1)
print("─ ─ ─ ▄ ▀ ▒ ▒ ▒ ▒ ▒ ▒ ▒ ▒ ▒ ▒ ▒ ▒ ▒ ▒ ▒ ▀ █ █ ▀ ▒ ▌ ─ ─ ─")
print(" ")
sleep(0.1)
print("─ ─ ▐ ▒ ▒ ▒ ▄ ▄ ▄ ▒ ▒ ▒ ▒ ▒ ▒ ▒ ▒ ▒ ▒ ▒ ▒ ▒ ▀ ▄ ▒ ▒ ▌ ─ ─")
print(" ")
sleep(0.1)
print("─ ─ ▌ ▒ ▒ ▐ ▄ █ ▀ ▒ ▒ ▒ ▒ ▄ ▀ █ ▄ ▒ ▒ ▒ ▒ ▒ ▒ ▒ █ ▒ ▐ ─ ─")
print(" ")
sleep(0.1)
print("─ ▐ ▒ ▒ ▒ ▒ ▒ ▒ ▒ ▒ ▒ ▒ ▒ ▌ █ █ ▀ ▒ ▒ ▒ ▒ ▒ ▒ ▒ ▒ ▀ ▄ ▌ ─")
print(" ")
sleep(0.1)
print("─ ▌ ▒ ▀ ▄ █ █ ▄ ▒ ▒ ▒ ▒ ▒ ▒ ▒ ▒ ▒ ▒ ▒ ░ ░ ░ ░ ▒ ▒ ▒ ▒ ▌ ─")
print(" ")
sleep(0.1)
print("─ ▌ ▀ ▐ ▄ █ ▄ █ ▌ ▄ ▒ ▀ ▒ ▒ ▒ ▒ ▒ ▒ ░ ░ ░ ░ ░ ░ ▒ ▒ ▒ ▐ ─")
print(" ")
sleep(0.1)
print("▐ ▒ ▀ ▐ ▀ ▐ ▀ ▒ ▒ ▄ ▄ ▒ ▄ ▒ ▒ ▒ ▒ ▒ ░ ░ ░ ░ ░ ░ ▒ ▒ ▒ ▒ ▌")
print(" ")
sleep(0.1)
print("▐ ▒ ▒ ▒ ▀▀ ▄ ▄ ▒ ▒ ▒ ▄ ▒ ▒ ▒ ▒ ▒ ▒ ░ ░ ░ ░ ░ ░ ▒ ▒ ▒ ▐ ─")
print(" ")
sleep(0.1)
print("─ ▌ ▒ ▒ ▒ ▒ ▒ ▒ ▀ ▀ ▀ ▒ ▒ ▒ ▒ ▒ ▒ ▒ ▒ ░ ░ ░ ░ ▒ ▒ ▒ ▒ ▌ ─")
print(" ")
sleep(0.1)
print("─ ▐ ▒ ▒ ▒ ▒ ▒ ▒ ▒ ▒ ▒ ▒ ▒ ▒ ▒ ▒ ▒ ▒ ▒ ▒ ▒ ▒ ▒ ▒ ▒ ▒ ▐ ─ ─")
print(" ")
sleep(0.1)
print("─ ─ ▀ ▄ ▒ ▒ ▒ ▒ ▒ ▒ ▒ ▒ ▒ ▒ ▒ ▒ ▒ ▒ ▒ ▒ ▒ ▄ ▒ ▒ ▒ ▒ ▌ ─ ─")
print(" ")
sleep(0.1)
print("─ ─ ─ ─ ▀ ▄ ▒ ▒ ▒ ▒ ▒ ▒ ▒ ▒ ▒ ▒ ▄ ▄ ▄ ▀ ▒ ▒ ▒ ▒ ▄ ▀ ─ ─ ─")
print(" ")
sleep(0.1)
print("─ ─ ─ ▐ ▀ ▒ ▀ ▄ ▄ ▄ ▄ ▄ ▄ ▀ ▀ ▀ ▒ ▒ ▒ ▒ ▒ ▄ ▄ ▀ ─ ─ ─ ─ ─")
print(" ")
sleep(0.1)
print("─ ─ ▐ ▒ ▒ ▒ ▒ ▒ ▒ ▒ ▒ ▒ ▒ ▒ ▒ ▒ ▒ ▒ ▒ ▀ ▀ ─ ─ ─ ─ ─ ─ ─ ─")
print(" ")
print("quu..__")
sleep(0.1)
print("$$$b  `---.__")
sleep(0.1)
print("  '$$b        `--.                          ___.---uuudP")
sleep(0.1)
print("   `$$b           `.__.------.__     __.---'      $$$$'          ")
sleep(0.1)
print("     '$b          -'            `-.-'            $$$'              .'|")
sleep(0.1)
print("       '.                                       d$'             _.'  |")
sleep(0.1)
print("         `.   /                              ...'              '     |")
sleep(0.1)
print("           `./                           ..::-'            _.'       |")
sleep(0.1)
print("            /                         .:::-'            .-'         .'")
sleep(0.1)
print("           :                          ::''\          _.'            |")
sleep(0.1)
print("          .' .-.             .-.           `.      .'               |")
sleep(0.1)
print("          : /'$$|           .@'$\           `.   .'              _.-'")
sleep(0.1)
print("         .'|$u$$|          |$$,$$|           |  <            _.-'")
sleep(0.1)
print("         | `:$$:'          :$$$$$:           `.  `.       .-'")
sleep(0.1)
print("         :                  ''--'             |    '-.     \ ")
sleep(0.1)
print("        :##.       ==             .###.       `.      `.    `\   ")
sleep(0.1)
print("        |##:                      :###:        |        >     >")
sleep(0.1)
print("        |#'     `..'`..'          `###'        x:      /     /")
sleep(0.1)
print("         \                                   xXX|     /    ./")
sleep(0.1)
print("          \                                xXXX'|    /   ./")
sleep(0.1)
print("          /`-.                                  `.  /   /")
sleep(0.1)
print("         :    `-  ...........,                   | /  .'")
sleep(0.1)
print("         |         ``:::::::'       .            |<    `.")
sleep(0.1)
print("         |             ```          |           x| \ `.:``.")
sleep(0.1)
print("         |                         .'    /'   xXX|  `:`M`M':.")
sleep(0.1)
print("         |    |                    ;    /:' xXXX'|  -'MMMMM:'")
sleep(0.1)
print("         `.  .'                   :    /:'       |-'MMMM.-'")
sleep(0.1)
print("          |  |                   .'   /'        .'MMM.-'")
sleep(0.1)
print("          `'`'                   :  ,'          |MMM<")
sleep(0.1)
print("            |                     `'            |tbap\   ")
sleep(0.1)
print("             \                                  :MM.-'")
sleep(0.1)
print("              \                 |              .''")
sleep(0.1)
print("               \.               `.            /")
sleep(0.1)
print("                /     .:::::::.. :           /")
sleep(0.1)
print("               |     .:::::::::::`.         /")
sleep(0.1)
print("               |   .:::------------\       /")
sleep(0.1)
print("              /   .''               >::'  /")
sleep(0.1)

print("                z   $b$$F")
sleep(0.1)
print("               F'  4$$P'")
sleep(0.1)
print("                r *$$$'.c...")
sleep(0.1)
print("                %-4$$$$$$$$'")
sleep(0.1)
print("                 J$*$$$$$$P")
sleep(0.1)
print("                ^r4$$$$$$'")
sleep(0.1)
print("                  *f*$$*'")
sleep(0.1)
print("                '.4 *$$$$$$.")
sleep(0.1)
print("          4ee%.e.  .$$$$$$$$r")
sleep(0.1)
print("         4$$$$$$b  P$**)$$$$b")
sleep(0.1)
print("      e..4$$$$$$$'     $$$$$$c.")
sleep(0.1)
print("      3$$$$$$$$*'      ^'$$$$$$c")
sleep(0.1)
print("     *$$$$$$$$$.        *$$$$$$$.")
sleep(0.1)
print("      ..$$$$$$$L    c ..J$$$$$$$b")
sleep(0.1)
print("      d'$$$$$$$F   .@$$$$$$$$$$$P'..")
sleep(0.1)
print("   ..$$$$$$$$$$      d$$$$$$$$$$$$$$$")
sleep(0.1)
print("   =$$$$$$P"" '    .e$$$$$$$$$$$$$$$$")
sleep(0.1)
print("     *""          $**$$$$$$$$$$$$$$*")
sleep(0.1)
print("                     "".$$$$$$$$$C .")
sleep(0.1)
print("                   .z$$$$$$$$$$$$$$""")
sleep(0.1)
print("                  .$$$*'^**'  '")
sleep(0.1)
print("                =P"  "")
sleep(0.1)
print("________________________")
sleep(0.1)
print("|\\\\    |    |    ////|")
sleep(0.1)
print("|___\\\\_|    |_////___|")
sleep(0.1)
print("|~~~~~~~~      ~~~~~~~~|")
sleep(0.1)
print("|________      ________|")
sleep(0.1)
print("|~~~////~|    |~\\\\~~~|")
sleep(0.1)
print("|////    |    |    \\\\|")
sleep(0.1)
print("``````````````````````` ")
