f=open("form.txt","w")
first=input("first name")
second=input("second name")
gender=input("gender")
form=input("form")
f.write("first name.\n")
f.write(first)
f.write("\n")
f.write("second name\n")
f.write(second)
f.write("\n")
f.write("gender\n")
f.write(gender)
f.write("\n")
f.write("form\n")
f.write(form)
f.close()
